### PR TITLE
fix/connection-status

### PR DESCRIPTION
**Pull request by xalpol12**
> Will bump to v0.2.0 after pull request is accepted

# Changes

## Unity
- Closing #36 (kind of - status in UI does not update automatically, it has to be refreshed by swiping up the main menu and retracting it once again, maybe @CoyotWilly will take a look while doing manual tests on Android with a real robot)
- Now image is recognised only for a selected robot, no other images will be recognised
- After selecting another robot from main list, previously tracked robot's prefabs will be cleared 
- After selecting another robot from main list, request to stop receiving informations about previously tracked robot will be sent
- Deleted obsolete `MainThreadDispatcher` class used to dispatch multithreaded processes, which was a more complicated way of creating a Coroutine - now directly using Coroutine

## KukaComm
- Fixed incorrect `.properties` in kukaComm test folder - introduced h2 and mariadb setup to choose from
- Fixed failing test, added test to assert that already existing robot exception is thrown

### CODE REVIEW

**Comment by CoyotWilly** [comment]
If we wait until Tuesday, then we can also try out the pipeline as it's done, but it needs admin privileges to set it up properly. So my suggestion is: I'll review it, but if you could wait with merge unitl October 3, then we'll make a pipeline branch merge and set up ( probably during 1 lecture ).

**Comment by xalpol12** [comment]
Ok, it makes no difference to me, we can also just merge this to main and the mergen your pipe branch to main as you already rebased it - the order doesn't matter to me.

**Review by CoyotWilly — APPROVED** [review]
### Review conclusion
All listed features and changes are working as desired. Connection status has some problems that I [@CoyotWilly ] will take care later, probably during in lab tests. Code looks clean and covers last meeting (09/30/2023) conserns about pipeline #42 artifacts build and deploy. 

### Notes 🧾 
Ready to merge ✅, but i would like to ask for a favor to hold merge action until pipeline setup to check does it work the same way like on my fork of this repo.

**Comment by xalpol12** [comment]
Thanks for the review. Yeah, sure, I will hold on with merging this branch until tomorrow, no problem.

**Pull request merged**
