### PR TITLE
Java pipeline

### PR DESCRIPTION
**Pull request by CoyotWilly**
## Java pipeline logic
1. Runs tests
2. Builds `.jar` file
3. `@Optional @NotImplemented ` Deploys docer image

## View of final pipe: {Just an idea 💡 }
1. Runs java tests
2. Runs Unity AR tests
3. Runs Unity UI tests
4. Builds `.jar` file
5. Builds `.apk` file
6. Deploys containers to docer:
  - database update
  - client apk
  - java backend
  - `@Optional` NoSQL database update

### CODE REVIEW

**Review by xalpol12 — COMMENTED** [review]
This pull would change our database to a MariaDB. As we discussed, we want to keep H2. 

Also the http "/update" method was changed from @PostMapping to @PutMapping, is this the change that you approve @przWaw?

**Comment by CoyotWilly** [comment]
Discard them during rebase IDE staged by local changes, they weren't intended to be pushed

**Comment by CoyotWilly** [comment]
Discard them during rebase IDE staged by local changes, they weren't intended to be pushed

**Comment by xalpol12** [comment]
ok
Tell me, there are two branches: "pipline" and "pipeline". Which one is developed?

**Comment by przWaw** [comment]
I don't mind either way, if you're saying it's more intuitive and follows commercial standards then we can change it.

**Pull request closed without merging**
