### PR TITLE
Bug fixes of UI after AR+UI merge

### PR DESCRIPTION
**Pull request by CoyotWilly**
### Fixed:
- Jogs display no longer  requires to double click after opening bottom nav while jogs were open
- First notification is now swipeable
- UI displays proper connection status after choosing a robot from list

### Added:
- Notification system
- Data fetch animation while requesting manually

### CODE REVIEW

**Comment by xalpol12** [comment]
Ip configuration screen does not let me click "Save" button. Turns out script for `AnchorManager` in XR Origin was lost, so I added it back. Now building app to check if this solve the problem. Will push changes to this branch in a few minutes, if my solution is right.

**Review by xalpol12 — CHANGES_REQUESTED** [review]
Feedback from Android app:
* does not display list of robots - stuck on infinite load animation
* first popup notification can't be deleted (swipe does not work)
* AR functionality is not invoked when "Save" button is clicked in config screeen
I will work on AR functionality to be invoked tomorrow - first thing in the morning. First 2 points are working in Unity Editor, but strangely not on Android.

**Comment by CoyotWilly** [comment]
The first 2 points are exactly what i was afraid of . If it's not a problem pls leave this branch I will try to fix those issues as the first one at morning. They gonna be my priority as I would like to merge this branch by the end of Sunday. A move forward to what we discussed today.

**Comment by xalpol12** [comment]
Yeah sure, I won't delete this branch and try to work some of the problems myself tomorrow

**Review by xalpol12 — APPROVED** [review]
* [x] FIXED does not display list of robots - stuck on infinite load animation [on this branch](https://github.com/xalpol12/kuka-ar-all/tree/fix/issue-%2327)

* [x] FIXED first popup notification can't be deleted (swipe does not work)

* [x] FIXED AR functionality is not invoked when "Save" button is clicked in config screeen

**Pull request merged**
