### PR TITLE
feature/subscribing-base-tcp-number

### PR DESCRIPTION
**Pull request by xalpol12**
Created two new events in `TrackedRobotsHandler` to retrieve information about currently selected BASE and TOOL value from websocket.

```cs
public event EventHandler<KRLInt> ActiveBaseUpdated;
public event EventHandler<KRLInt> ActiveToolUpdated;
```

Integration with UI is done analogically to `ActiveJointsUpdated`:
- subcribing to `ActiveBaseUpdated` returns KRLInt value when active base number changes
- subscribing to `ActiveToolUpdated` returns KRLInt value when active tool number changes

You just have to process those values in UI

Code has been tested in Unity Simulation Environment, it returns new value on websocket value change

### CODE REVIEW

**Comment by xalpol12** [comment]
Lmk if something's wrong with the code

**Review by CoyotWilly — APPROVED** [review]
## Review 🧾 
Adds all functionality that was mentioned during meeting, which are an event properities for UI tool and base number display on topbar.

## Result 
Done 👍 
Works ✅

**Comment by CoyotWilly** [comment]
I'll be done with UI for top bar before today evening (10/08/2023), but also would like to know do y need any event/s for selected coords systems as y can select between _$BASE, $TOOL, $WORLD_ and if so then in what form an _Dictionary<string, objetc>_ or 3 seperate events each for different coord system.

**Comment by xalpol12** [comment]
Right now I don't know, we will have to discuss it

**Pull request merged**
