### PR TITLE
feature/delete-anchor-on-refresh-button-click

### LINKED ISSUE #56: [Unity] Assets too heavy
## Problem ⚠️ 
Currently assets weight is about 91.4% of total app size, we should reduce that.
Should be done: 🔖 
- image commpression should be applied
- if possiblem size should be reduced as some assets are very big eventhough they don't have to be becouse their usege is even not a 10% of their size

### LINKED ISSUE #57: [Unity] Delete configured anchor on refresh button click
As suggested in a meeting during lab testing on 17.10, it would be helpful to have anchor deletion action connected to refresh button so that we don't have to restart app every time the anchor is placed incorrectly

### PR DESCRIPTION
**Pull request by xalpol12**
## Changes
- Assets weight reduction, closes #56 
- Ability to delete anchor on 'refresh' button from tracked robots list, closes #57 

The problem here is that while we can reset prefabs for instantiated objects and anchor, we can’t delete already detected image from our image library - [link](https://github.com/Unity-Technologies/arfoundation-samples/issues/385), from what I've researched, AR Foundation API for `AR tracked image manager` does not provide any method for this. So either we create a major workaround (creating new mutable image library each time user clicks reset button (to allow him to detect that image once again) or we leave it for now)

## Next
- Rotation fix

### CODE REVIEW

**Comment by CoyotWilly** [comment]
## Comment
Are we merging this pull request ?? As for now i don't really see any sens. I would like to wait to fix our major consern which is rotation problem and when this will be solved submit pull request with _#Beta_ version release.

## Accidental detect 🕵️ 
####How about this 💡 
You are checking was **ANY** item from list chosen, and if not then do not call `add new trackable object` function. In other scenario when item was chosen everythink work just like now. 

## Review 🏁 
All looks good tommorow, i'll make an offical review.

**Comment by xalpol12** [comment]
Yeah, we can hold on for a while with merging this branch, I just thought I would give an update on the situation. 

Regarding the detection when no robot is selected - I can't really access the lifecycle of detected image _before_ it is detected, I think I can disable detection in case user has not yet selected any robot though. But it's just a detail, right now (tomorrow) I would like to focus on debugging rotations.

**Review by CoyotWilly — COMMENTED** [review]
## Review 🏁 
- Assets weight is smaller #56  ✅ 
- Anchor is deleted on _refresh button_ click #57 🛑 

## Waiting for ⏰ 
Rotation fix - included in the explanation 🤙 

## Conclusion 🧾 
Ready to merge, to master or to fix/rotation branch and then to master

**Review by CoyotWilly — APPROVED** [review]
## Review 🏁 
- Assets weight is smaller #56  ✅ 
- Anchor is deleted on _refresh button_ click #57 🛑 

## Waiting for ⏰ 
Rotation fix - included in the explanation 🤙 

## Conclusion 🧾 
Ready to merge, to master or to fix/rotation branch and then to master

**Pull request closed without merging**
