### PR TITLE
UI v3 partial update

### PR DESCRIPTION
**Pull request by CoyotWilly**
### Questions about UI:
- how to wrap it into courtines if UI highly relies on frame rate which means that is stringly connected with UPDATE function??
- **2x CHECK** the Api based features like selecting or add robot data add window sliding as i weren't able to do so
- can we land directly in menu after clicking 'back arrow' in webView scene or should we land in 'moreOptions' ??

### Another scene
Unfortunatly is nessesary as WebView lib show on screen as stays like that no matter what's having place in scene. Like i opened it clicked back arrow to go back to more options tab and "guess what" browser window were there too. So i wraped it into a prefab as i wanted at the beginning and thew it into new sepate scene where it can couse damage as there is literraly nothing.

### CODE REVIEW

**Comment by xalpol12** [comment]
Answers to your questions:
* which methods do you want to invoke using coroutines? if you mean the http calls, then I have implemented a RestClient that uses command design pattern (each type of resource server call is a separate command - i.e. get images, get configured robot data and so on) and we could use this RestClient through the whole app
* checking now
* it doesn't matter to me, @przWaw do you have any suggestion where app should land after returning from web view?


I don't understand the 'another scene' paragraph. What is the issue there?

**Comment by xalpol12** [comment]
I do have a question though, what the hell is going on in WebViewObject.cs, wouldn't intent action be simpler?

**Comment by xalpol12** [comment]
Oh I get it now, so you had to create another scene to redirect user to WebView upon clicking link to "Report a bug" section. So my question stands still: wouldn't intent simplify things? like a lot?

**Comment by przWaw** [comment]
**how to wrap it into courtines if UI highly relies on frame rate which means that is stringly connected with UPDATE function??**
* I would wrap UI animation methods into coroutines. Coroutines are strongly connected with frame rate by themselves. One can simply make while loop inside the coroutine and call "yield return null" inside loop to break execution in current frame and return to execution of method from the same point in next frame. 
* 
**can we land directly in menu after clicking 'back arrow' in webView scene or should we land in 'moreOptions' ??**
* I agree with @xalpol12 that intents and opening of default web browser on mobile device would be simpler and more readable for user. But answering question - we should land in the same place from which we start - so if start was in moreOptions it should be moreOptions etc.

**Pull request merged**
