### PR TITLE
Feature/UI v3

### PR DESCRIPTION
**Pull request by CoyotWilly**
## Polished: 🏁 🔢 
- assets
- real app UI behavior
- performance

## Having trouble with: 👀 🔍 
- build crash bc of missing shadere dependecies

## TODO: 📓 🚀 
- jogs are not done at all (hopefuly soon we will make a meeting with @xalpol12 and fix that)
- general service dictionary clean up (starting  from cleaner and more effective HTTP service)
- Unit test for Unity (rebase need that's why i post this pull request)

### CODE REVIEW

**Comment by xalpol12** [comment]
@CoyotWilly check if branch with resolved conflicts works as intended.

**Comment by CoyotWilly** [comment]
Yes sir

**Comment by CoyotWilly** [comment]
@xalpol12 sth went really bad, I pulled all commits and now I have over 900 errors in 21 files, all of them caused by namespaces or missing dependencies or who know what else. WFT is wrong that even accessors are marked invalid, example:
`private Start()` is invalid TF is going on ???

**Comment by xalpol12** [comment]
ok. let's revert to [5724575](https://github.com/xalpol12/kuka-ar-all/pull/19/commits/572457598ba69ae6b694ea4d2c1ae26a67c24acb)

**Comment by CoyotWilly** [comment]
What's the plan to solve this issue with merge ??
As I would like to know how to get started tommorow?? New branch ?? Day off ?? Or what?? @xalpol12

**Comment by xalpol12** [comment]
The plan to solve this issue is to for me to go back to the previous commit and rebase with force push now

**Comment by CoyotWilly** [comment]
Ok, unless you will wait a moment, and I'll try to solve this conflicts but before that, I'll wrap all Unity classes into namespaces

**Comment by xalpol12** [comment]
Ok, let me know when you are finished

**Comment by CoyotWilly** [comment]
Ok so it went really smooth, I made rebase and now everything should be OK. Could you check it @xalpol12 ?? And if you don't have any errors then merge it pls and delete this branch.

**Comment by xalpol12** [comment]
No errors, functionalities seem to be working the way it's intended. Merging now.

**Review by xalpol12 — APPROVED** [review]

**Pull request merged**
